### PR TITLE
make color label readable

### PR DESCRIPTION
**Pull request by jkl3848**
Addresses issue #16. Made all hexcodes black. Not a very fancy solution, but I thought since the active color was shown in color preview, it wasn't as necessary to maintain the colors in the hexcode.

image

### CODE REVIEW

**Comment by Kully** [comment]
> Addresses issue #16. Made all hexcodes black. Not a very fancy solution, but I thought since the active color was shown in color preview, it wasn't as necessary to maintain the colors in the hexcode.

@jkl3848 Thanks for taking this on (as well as the other PR which just got submitted).

Hmm, I think this solution makes sense. I did want to have that double correspondence with coloring the text the same as what you have selected, but to your point, we _do_ already have cues as to what color you have picked (both the white border around the selected color preview and the fact that it looks a little bigger due to picking the color)

Since this solves the problem, I'm good to mark this as complete. 👍

**Review by Kully — APPROVED** [review]

**Comment by Kully** [comment]
@jkl3848 Okay, I made the change I suggested and committed to this branch. I hope that is okay with you.

If everything is good, I am happy to merge this PR! Thank you for the work. 👍

**Comment by jkl3848** [comment]
@Kully Yeah looks good

**Comment by jkl3848** [comment]
@Kully This is an unimportant change, but would you mind if I change the font of the hexcode? To something a little more on theme?

**Comment by jkl3848** [comment]
> PS The rationale for Menlo (equally spaced font) is because that's the font used in text editors, and hex feels like a programmy font 🤓

That makes sense. Then maybe we should switch it to ` font-family: Menlo, sans-serif;`

image

Typically serif fonts are used for print, so it has kind of a dated web look. Going with sans-serif makes it look more digital, which not only looks better on screens, but also fits the pixel art aesthetic.

Another option is to add monospace too, which would give it even more of a programmy feel.

image

**Comment by Kully** [comment]
Here we go! 💃

**Pull request merged**
