### PR TITLE
Updated README with New GIF Preview

### PR DESCRIPTION
**Pull request by Aden1ke**
Description:

I have updated the README file by adding an up-to-date GIF of the Pixel Paint tool as requested. The new GIF provides a clear, accurate preview of the current interface and key features.

Let me know if you'd like any further modifications or additional media to be included.

### CODE REVIEW

**Comment by Kully** [comment]
Fixes #40

**Comment by Aden1ke** [comment]
I misunderstood your request for a new GIF, I didn’t realize you meant creating a completely new GIF. I’ll get started on creating one and will update the README as soon as it’s ready.

Thank you for your patience!

**Comment by Aden1ke** [comment]
Hey @Kully, I’m not sure if this is exactly what you meant, but I’ve gone ahead and created a new GIF. Let me know your thoughts!

**Comment by Kully** [comment]
> Hey @Kully, I’m not sure if this is exactly what you meant, but I’ve gone ahead and created a new GIF. Let me know your thoughts!

Hey @Aden1ke ! Looks cool. I like how you cycled through all the features. My only concerns right now are:
- there are faint vertical lines showing up on the canvas in the GIF - do you know what that could be about
- the picture is not as recognizable as the Super Mario Bros coins that are currently being drawn in the current GIF

Hmmm, I am now wondering if it might be better to simply just replace the GIF with one or two still images instead? GIFs can come out a little shaky since they they have to be so compressed.

I'm curious, what do you think about this?

**Comment by Aden1ke** [comment]
Hey @Kully  Thanks for pointing that out. What I’ve noticed is that any color apart from white seems to show those vertical lines. The Super Mario Bros coins look much clearer, as you mentioned. I’ll try creating another GIF with a clearer output to see if that helps resolve the issue. However, if I can’t improve the quality, I agree with you—it might be best to stick with the Super Mario coins.

**Comment by Kully** [comment]
Got you.

You know what, on second thought, I think I should be taking this task on.
While I appreciate the help, this has more to do with creative control and
presentation of the project, which is more in the author’s wheelhouse.

Let’s close this PR for now, and I will think of a solution on my own time.
I appreciate your help though. 🙏

**Comment by Aden1ke** [comment]
Got it, @Kully, I completely understand where you’re coming from. Creative control and presentation are definitely key aspects of the project, and it makes sense for you to take the lead on that. Let’s go ahead and close this PR, and I’ll leave it in your capable hands. If you ever want a second set of eyes or any assistance down the road, feel free to reach out. Thanks for the opportunity to help, and best of luck with the final touches!

**Comment by Kully** [comment]
Appreicate it a lot!

Are there any other open issues you would like me to work on?

Also, do you use pixel paint? What you like about it / wish it had? That’s
probably a good starting point as well - it’s important for me to know how
people are using this tool so we can make it better. :)

**Comment by Aden1ke** [comment]
I noticed that whenever I draw with a different color on top of another layer and use the eraser, it erases both the drawing color and the layer underneath. Is there a way to make the eraser only affect the drawing color without erasing the other colored layer?

**Comment by Kully** [comment]
> I noticed that whenever I draw with a different color on top of another layer and use the eraser, it erases both the drawing color and the layer underneath. Is there a way to make the eraser only affect the drawing color without erasing the other colored layer?

The reason that is happening is because pixel paint doesn't support layers. There is only one layer so if you erase it, you erase everything.

However, there is an issue open for this already: https://github.com/Kully/pixel-paint/issues/7

**Comment by Kully** [comment]
Closing as the requirements for the issue changed.

**Pull request closed without merging**
