### PR TITLE
add shortcut legend

### PR DESCRIPTION
**Pull request by jkl3848**
I thought it might be handy to have the keyboard shortcuts list on the page itself, instead of having to reference the git repo. I tried to keep the style simple.

### CODE REVIEW

**Comment by Kully** [comment]
@jkl3848 Good idea and would probably be helpful.

I have a couple comments:
1. We should probably allow it to be collapsable.
2. It right now sits too far low. Maybe it makes sense to fix its position.

Maybe something like this? What do you think?

image

**Comment by Kully** [comment]
@jkl3848 Hey just checking in? Are you still tryin to get this merged (and the other one you started #29 )

**Comment by jkl3848** [comment]
> @jkl3848 Hey just checking in? Are you still tryin to get this merged (and the other one you started #29 )

Sorry I've been MIA. Been busy with some other projects. Yes I hope to finish these up soon.

**Comment by Kully** [comment]
> Sorry I've been MIA. Been busy with some other projects. Yes I hope to finish these up soon.

Sounds good! No worries, we are all busy people 🙏

Reviewing the PR again, it already looks like we are indicating the shortcuts for _some_ of the commands: if you hover over some of the buttons, it shows you the commands.

example:
image

But some of them are not indicated, as you have indicated in the legend.

To not repeat ourselves, we could maybe just keep these 3 in the shortcut:

image

Curious what you think :)

**Comment by jkl3848** [comment]
Just to make sure I understand, you're saying just keep those three in the legend, since the others are already in tooltips?

**Comment by Kully** [comment]
Yes. Thoughts?

**Comment by jkl3848** [comment]
Sounds good. I'll make the change

**Comment by jkl3848** [comment]
@Kully Ok I removed the extra shortcuts and switched to a onHover popover. Let me know what you think.

I dont mind replacing the word with an icon, I just wasn't sure what you use for icons.

**Comment by Kully** [comment]
> @Kully Ok I removed the extra shortcuts and switched to a onHover popover. Let me know what you think.
> 
> I dont mind replacing the word with an icon, I just wasn't sure what you use for icons.

Thanks for removing the extra shortcuts.

I felt the placement on the screen however was a little unintuitive in that it is not obvious that something will happen when you hover or click on it (not your fault, I didn't give a design requirement for this task).

I did some tweaking in CSS. Do you mind applying these changes? Once you do, we should be ready to merge. 🙌

Screen Shot 2024-10-07 at 11 59 34 AM

**Comment by jkl3848** [comment]
> > @Kully Ok I removed the extra shortcuts and switched to a onHover popover. Let me know what you think.
> > I dont mind replacing the word with an icon, I just wasn't sure what you use for icons.
> 
> Thanks for removing the extra shortcuts.
> 
> I felt the placement on the screen however was a little unintuitive in that it is not obvious that something will happen when you hover or click on it (not your fault, I didn't give a design requirement for this task).
> 
> I did some tweaking in CSS. Do you mind applying these changes? Once you do, we should be ready to merge. 🙌
> 
> Screen Shot 2024-10-07 at 12 06 17 PM

LGTM 👍🏻

**Comment by Kully** [comment]
> LGTM 👍🏻

Let me know if you are able to make these changes and we can go from there.

(PS I don't think I have permissions to, otherwise I would have done it 😛)

**Comment by jkl3848** [comment]
@Kully Ok should be good to go

**Comment by Kully** [comment]
> @Kully Ok should be good to go

Superb! Thank you!! 💃

**Review by Kully — APPROVED** [review]
LGTM!

**Pull request merged**
